# Generated by Django 2.2.2 on 2019-06-27 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='resource_type',
            new_name='content',
        ),
    ]
