# Generated by Django 2.2.2 on 2019-06-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20190627_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('PDF', 'PDF'), ('EPUB', 'EPUB')], default='PDF', max_length=25),
            preserve_default=False,
        ),
    ]
